webtalk_init -webtalk_dir c:/users/user/desktop/studia/sdup/last_one/ip_repo/edit_signal_ip_v1_0.sim/sim_1/behav/xsim/xsim.dir/signal_ip_v1_0_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Sep  7 16:26:55 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f4231c13-496c-44a2-a249-d9582691b389" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c81c67cf775943d59c6e26baa3c3c1c0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 4700U with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1996 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "5" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "108 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "6 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "51" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "47356_KB" -context "xsim\\usage"
webtalk_transmit -clientid 175560437 -regid "" -xml c:/users/user/desktop/studia/sdup/last_one/ip_repo/edit_signal_ip_v1_0.sim/sim_1/behav/xsim/xsim.dir/signal_ip_v1_0_behav/webtalk/usage_statistics_ext_xsim.xml -html c:/users/user/desktop/studia/sdup/last_one/ip_repo/edit_signal_ip_v1_0.sim/sim_1/behav/xsim/xsim.dir/signal_ip_v1_0_behav/webtalk/usage_statistics_ext_xsim.html -wdm c:/users/user/desktop/studia/sdup/last_one/ip_repo/edit_signal_ip_v1_0.sim/sim_1/behav/xsim/xsim.dir/signal_ip_v1_0_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
