# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2.xci
# IP: The module: 'mb_design_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2.xci
# IP: The module: 'mb_design_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Magda/Desktop/Projekt_SDUP/SDUP_Project/AXI/signal_acc/signal_acc.srcs/sources_1/bd/mb_design/ip/mb_design_axi_gpio_0_2/mb_design_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
